### ISSUE TITLE
New portal in 7.1

### ISSUE THREAD

**Issue by zp** [Kruithne/Telemancy#11]
The patch 7.1 Suramar story continuation replaces the Waning Crescent portal with a new one called "Evermoon Terrace" once you start quest http://www.wowdb.com/quests/38649-silence-in-the-city and finish http://www.wowdb.com/quests/42889-the-way-back-home

```
{ teleX = 52.00, teleY = 78.76, teleName = "TELE_EVERMOON_TERRACE", questID = 42889 }
```

**Comment by Kruithne** [comment]
Just to clarify, once you accept the first quest (38649) the portal is then active all the time? Or does it stop being active at some point after (42889)?

**Comment by zp** [comment]
I believe after accepting (38649) the Waning Crescent portal disappears forever, then after (42889) the Evermoon Terrace portal is active and takes its place forever. (it's in the same position as where the Waning Crescent portal was in Shal'Aran)

**Comment by Kruithne** [comment]
Okay, thanks for the clarification. I shall get that updated shortly.

**Comment by Kruithne** [comment]
A new version of Telemancy which addresses this has been released and should be coming down the pipes shortly.
