### ISSUE TITLE
Taint

### ISSUE THREAD

**Issue by Stanzilla** [Kruithne/Telemancy#4]
Telemancy is tainting the World Map, which happens quite easily, my guess is that it's coming from touching API while in combat,

**Comment by Kruithne** [comment]
Are you able to provide any more specific information on the taint? I'm not entirely sure where it's occurring, I can't replicate anything on this end.

**Comment by Stanzilla** [comment]
I don't have /taintlog enabled but the error looks like this 

```
2x [ADDON_ACTION_BLOCKED] AddOn 'Ace3' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function `Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function `SetMapAreaID'
FrameXML\WorldMapFrame.lua:390: in function <FrameXML\WorldMapFrame.lua:353>
[C]: ?
[C]: ?
[C]: in function `Hide'
FrameXML\UIParent.lua:2320: in function `SetUIPanel'
FrameXML\UIParent.lua:2347: in function `MoveUIPanel'
FrameXML\UIParent.lua:2378: in function `HideUIPanel'
FrameXML\UIParent.lua:2052: in function <FrameXML\UIParent.lua:2044>
[C]: in function `SetAttribute'
FrameXML\UIParent.lua:2846: in function `HideUIPanel'
FrameXML\WorldMapFrame.lua:305: in function <FrameXML\WorldMapFrame.lua:305>

Locals:
```

**Comment by Kruithne** [comment]
I don't see anything in this to indicate that it's Telemancy. Nothing is hooked into `WorldMapFrame.lua`, everything is reactive using events. The only thing that is remotely touching the map is child objects that we attach to `WorldMapPOIFrame`, but I don't see any mention of that here.

**Comment by Stanzilla** [comment]
Yeah well, that's the thing with taint, error logs are worthless and taint logs point to different addons all the time, too. I might try using it again and enable taint logging.

**Comment by Kruithne** [comment]
I would expect there to be at least some link though. Let me know if you find anything more.
